id: P002918
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC333
  title: 'རྗེ་བཙུན་གྲུབ་པའི་དབང་ཕྱུག་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེའི་རྣམ་ཐར། '
  author: ''
  volumes:
    b5bd7abf654149129cbd65f2121ba025:
      image_group_id: I2PD18631
      title: ''
      volume_number: 1
      total_pages: 204
      base_file: v001.txt
